//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covidien.CGRS.ESS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covidien.CGRS.ESS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _980_connectivity_1 {
            get {
                object obj = ResourceManager.GetObject("_980_connectivity_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _980_connectivity_2 {
            get {
                object obj = ResourceManager.GetObject("_980_connectivity_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _980_connectivity_3 {
            get {
                object obj = ResourceManager.GetObject("_980_connectivity_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _980_connectivity_4 {
            get {
                object obj = ResourceManager.GetObject("_980_connectivity_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _980_connectivity_5 {
            get {
                object obj = ResourceManager.GetObject("_980_connectivity_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ADD_BUTTON {
            get {
                return ResourceManager.GetString("ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string ADD_DEVICE_BUTTON {
            get {
                return ResourceManager.GetString("ADD_DEVICE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Download: .
        /// </summary>
        public static string AGENT_STATUS_DOWNLOAD {
            get {
                return ResourceManager.GetString("AGENT_STATUS_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Upload: .
        /// </summary>
        public static string AGENT_STATUS_UPLOAD {
            get {
                return ResourceManager.GetString("AGENT_STATUS_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the application?.
        /// </summary>
        public static string APP_CLOSE_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("APP_CLOSE_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software License Agreement acceptance needed to continue. Do you want to close the application?.
        /// </summary>
        public static string APP_CLOSE_MSGBOX_TEXT_EULA_CANCEL {
            get {
                return ResourceManager.GetString("APP_CLOSE_MSGBOX_TEXT_EULA_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Software License Agreement. Application will close..
        /// </summary>
        public static string APP_CLOSE_MSGBOX_TEXT_EULA_ERROR {
            get {
                return ResourceManager.GetString("APP_CLOSE_MSGBOX_TEXT_EULA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Confirmation.
        /// </summary>
        public static string APP_CLOSE_MSGBOX_TITLE {
            get {
                return ResourceManager.GetString("APP_CLOSE_MSGBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either User Cancelled or Invalid Authorization..
        /// </summary>
        public static string AUTH_INVALID_OR_CANCEL {
            get {
                return ResourceManager.GetString("AUTH_INVALID_OR_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth2LoginManager::Login Invalid Usertype:.
        /// </summary>
        public static string AUTH_INVALID_USERTYPE {
            get {
                return ResourceManager.GetString("AUTH_INVALID_USERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCancel.
        /// </summary>
        public static string AUTH_RESPONSE_USER_CANCEL {
            get {
                return ResourceManager.GetString("AUTH_RESPONSE_USER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth2LoginManager::Login Server Not Available.
        /// </summary>
        public static string AUTH_SERVER_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("AUTH_SERVER_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string AUTHENTICATING {
            get {
                return ResourceManager.GetString("AUTHENTICATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name/Password not recognized.
        /// </summary>
        public static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failure.
        /// </summary>
        public static string AUTHENTICATION_FAILURE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required.
        /// </summary>
        public static string AUTHENTICATION_REQUIRED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required for software update.
        /// </summary>
        public static string AUTHENTICATION_REQUIRED_FOR_SW {
            get {
                return ResourceManager.GetString("AUTHENTICATION_REQUIRED_FOR_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK_BUTTON {
            get {
                return ResourceManager.GetString("BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BROWSE_TO_UPDATE_DEVICE {
            get {
                return ResourceManager.GetString("BROWSE_TO_UPDATE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Documents Dialog.
        /// </summary>
        public static string CHOOSE_DOCUMENTS_DIALOG {
            get {
                return ResourceManager.GetString("CHOOSE_DOCUMENTS_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CLEAR_BUTTON {
            get {
                return ResourceManager.GetString("CLEAR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear logs on the device?.
        /// </summary>
        public static string CLEAR_LOGS_CONFIRMATION_MSG {
            get {
                return ResourceManager.GetString("CLEAR_LOGS_CONFIRMATION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE_BUTTON {
            get {
                return ResourceManager.GetString("CLOSE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor Operational Hours.
        /// </summary>
        public static string COMPRESSOR_OP_HOURS {
            get {
                return ResourceManager.GetString("COMPRESSOR_OP_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor Preventative Maintenance Hours.
        /// </summary>
        public static string COMPRESSOR_PM_HOURS {
            get {
                return ResourceManager.GetString("COMPRESSOR_PM_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor Serial Number.
        /// </summary>
        public static string COMPRESSOR_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("COMPRESSOR_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string CONNECT_BUTTON {
            get {
                return ResourceManager.GetString("CONNECT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string CONNECTING_BUTTON {
            get {
                return ResourceManager.GetString("CONNECTING_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting To Device.
        /// </summary>
        public static string CONNECTING_STATUS_MSG {
            get {
                return ResourceManager.GetString("CONNECTING_STATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datakey.
        /// </summary>
        public static string DATA_KEY {
            get {
                return ResourceManager.GetString("DATA_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string DEV_INFO_MODEL {
            get {
                return ResourceManager.GetString("DEV_INFO_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Num:.
        /// </summary>
        public static string DEV_INFO_SN {
            get {
                return ResourceManager.GetString("DEV_INFO_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Part Num:.
        /// </summary>
        public static string DEV_INFO_SW_PARTNUM {
            get {
                return ResourceManager.GetString("DEV_INFO_SW_PARTNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        public static string DEV_INFO_SW_UPDATE {
            get {
                return ResourceManager.GetString("DEV_INFO_SW_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Revision:.
        /// </summary>
        public static string DEV_INFO_SW_VER {
            get {
                return ResourceManager.GetString("DEV_INFO_SW_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection To Device Failed.
        /// </summary>
        public static string DEVICE_CONNECT_FAILURE {
            get {
                return ResourceManager.GetString("DEVICE_CONNECT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed. Please check connection and settings..
        /// </summary>
        public static string DEVICE_CONNECT_FAILURE_MESSAGE {
            get {
                return ResourceManager.GetString("DEVICE_CONNECT_FAILURE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected To Device.
        /// </summary>
        public static string DEVICE_CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Connected.
        /// </summary>
        public static string DEVICE_CONNECTED_STATUS {
            get {
                return ResourceManager.GetString("DEVICE_CONNECTED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disconnect from the device?.
        /// </summary>
        public static string DEVICE_DISCONNECT_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("DEVICE_DISCONNECT_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Disconnected.
        /// </summary>
        public static string DEVICE_DISCONNECTED_STATUS {
            get {
                return ResourceManager.GetString("DEVICE_DISCONNECTED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info.
        /// </summary>
        public static string DEVICE_INFO {
            get {
                return ResourceManager.GetString("DEVICE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataKey:.
        /// </summary>
        public static string DEVICE_KEY_TYPE {
            get {
                return ResourceManager.GetString("DEVICE_KEY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Retrieval From Device Failed.
        /// </summary>
        public static string DEVICE_LOG_RETRIEVAL_FAILURE {
            get {
                return ResourceManager.GetString("DEVICE_LOG_RETRIEVAL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Retrieval From Device Succeeded.
        /// </summary>
        public static string DEVICE_LOG_RETRIEVAL_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_LOG_RETRIEVAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Upload Failure. Restart ESS Application..
        /// </summary>
        public static string DEVICE_LOG_UPLOAD_FAILURE {
            get {
                return ResourceManager.GetString("DEVICE_LOG_UPLOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Required to Upload Logs To Server.
        /// </summary>
        public static string DEVICE_LOG_UPLOAD_LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("DEVICE_LOG_UPLOAD_LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Upload Successful.
        /// </summary>
        public static string DEVICE_LOG_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_LOG_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Upload In Progress....
        /// </summary>
        public static string DEVICE_LOGS_UPLOAD_INPROGRESS {
            get {
                return ResourceManager.GetString("DEVICE_LOGS_UPLOAD_INPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not reachable. Please check connection and settings..
        /// </summary>
        public static string DEVICE_NOT_REACHABLE_MESSAGE {
            get {
                return ResourceManager.GetString("DEVICE_NOT_REACHABLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Not Verified.
        /// </summary>
        public static string DEVICE_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("DEVICE_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Session.
        /// </summary>
        public static string DEVICE_OPEN_SESSION {
            get {
                return ResourceManager.GetString("DEVICE_OPEN_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service parameter update on device in progress....
        /// </summary>
        public static string DEVICE_PARAMETER_SETTING_IN_PROGRESS {
            get {
                return ResourceManager.GetString("DEVICE_PARAMETER_SETTING_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Registration Failed.
        /// </summary>
        public static string DEVICE_REGISTRATION_FAILURE {
            get {
                return ResourceManager.GetString("DEVICE_REGISTRATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Registration In Progress....
        /// </summary>
        public static string DEVICE_REGISTRATION_INPROGRESS {
            get {
                return ResourceManager.GetString("DEVICE_REGISTRATION_INPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial Number:.
        /// </summary>
        public static string DEVICE_SERIAL_NUMBER {
            get {
                return ResourceManager.GetString("DEVICE_SERIAL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Parameter Update Failed.
        /// </summary>
        public static string DEVICE_SETTING_FAILURE {
            get {
                return ResourceManager.GetString("DEVICE_SETTING_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Parameter Retrieval Failed.
        /// </summary>
        public static string DEVICE_SETTING_RETRIEVAL_ERROR {
            get {
                return ResourceManager.GetString("DEVICE_SETTING_RETRIEVAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service parameter retrieval from device is in progress....
        /// </summary>
        public static string DEVICE_SETTING_RETRIEVAL_IN_PROGRESS {
            get {
                return ResourceManager.GetString("DEVICE_SETTING_RETRIEVAL_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Parameter Retrieval Succeeded.
        /// </summary>
        public static string DEVICE_SETTING_RETRIEVAL_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_SETTING_RETRIEVAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Parameter Update Succeeded.
        /// </summary>
        public static string DEVICE_SETTING_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_SETTING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Types.
        /// </summary>
        public static string DEVICE_TYPES_LABEL {
            get {
                return ResourceManager.GetString("DEVICE_TYPES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Work List.
        /// </summary>
        public static string DEVICE_WORK_LIST_TITLE {
            get {
                return ResourceManager.GetString("DEVICE_WORK_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Logs Upload Failure. Restart ESS Application..
        /// </summary>
        public static string DIAGNOSTIC_LOGS_UPLOAD_FAILURE {
            get {
                return ResourceManager.GetString("DIAGNOSTIC_LOGS_UPLOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Logs Upload In Progress....
        /// </summary>
        public static string DIAGNOSTIC_LOGS_UPLOAD_INPROGRESS {
            get {
                return ResourceManager.GetString("DIAGNOSTIC_LOGS_UPLOAD_INPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Logs Upload Successful.
        /// </summary>
        public static string DIAGNOSTIC_LOGS_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("DIAGNOSTIC_LOGS_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DISCONNECT_BUTTON {
            get {
                return ResourceManager.GetString("DISCONNECT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document close error.
        /// </summary>
        public static string DOCUMENT_CLOSE_ERROR {
            get {
                return ResourceManager.GetString("DOCUMENT_CLOSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Control.
        /// </summary>
        public static string DOCUMENT_CONTROL {
            get {
                return ResourceManager.GetString("DOCUMENT_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document delete error.
        /// </summary>
        public static string DOCUMENT_DELETE_ERROR {
            get {
                return ResourceManager.GetString("DOCUMENT_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document open error.
        /// </summary>
        public static string DOCUMENT_OPEN_ERROR {
            get {
                return ResourceManager.GetString("DOCUMENT_OPEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DOCUMENTS_LABEL {
            get {
                return ResourceManager.GetString("DOCUMENTS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Mode.
        /// </summary>
        public static string DOWNLOAD_MODE {
            get {
                return ResourceManager.GetString("DOWNLOAD_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ESS_Branding {
            get {
                object obj = ResourceManager.GetObject("ESS_Branding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESS.
        /// </summary>
        public static string ESS_TITLE {
            get {
                return ResourceManager.GetString("ESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST performed on.
        /// </summary>
        public static string EST_PERFORMED_DATE {
            get {
                return ResourceManager.GetString("EST_PERFORMED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST Status.
        /// </summary>
        public static string EST_STATUS {
            get {
                return ResourceManager.GetString("EST_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Enhanced Service Mode?.
        /// </summary>
        public static string EXTEND_ENHANCED_SERVICE_MODE_QUESTION {
            get {
                return ResourceManager.GetString("EXTEND_ENHANCED_SERVICE_MODE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve.
        /// </summary>
        public static string FAILED_STATUS {
            get {
                return ResourceManager.GetString("FAILED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FILE_NOT_FOUND_ERROR_MSG {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested function is restricted.
        /// </summary>
        public static string FUNCTION_RESTRICTED_MSG {
            get {
                return ResourceManager.GetString("FUNCTION_RESTRICTED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not connected and this functionality is disabled.
        /// </summary>
        public static string FUNCTIONALITY_DISABLED_USING_DUMMY_DEVICE {
            get {
                return ResourceManager.GetString("FUNCTIONALITY_DISABLED_USING_DUMMY_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Log.
        /// </summary>
        public static string GET_LOG_BUTTON {
            get {
                return ResourceManager.GetString("GET_LOG_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting log,.
        /// </summary>
        public static string GET_LOG_MSG {
            get {
                return ResourceManager.GetString("GET_LOG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Devices.
        /// </summary>
        public static string INDIVIDUAL_DEVICES_LABEL {
            get {
                return ResourceManager.GetString("INDIVIDUAL_DEVICES_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Select Local File&gt;.
        /// </summary>
        public static string LOAD_LOCAL_FILE {
            get {
                return ResourceManager.GetString("LOAD_LOCAL_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string LOADED_STATUS {
            get {
                return ResourceManager.GetString("LOADED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  log.
        /// </summary>
        public static string LOG_NAME_POSTPEND {
            get {
                return ResourceManager.GetString("LOG_NAME_POSTPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string LOG_UPLOADED_STATUS {
            get {
                return ResourceManager.GetString("LOG_UPLOADED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string LOG_VIEW_FORM_TITLE {
            get {
                return ResourceManager.GetString("LOG_VIEW_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not read file from disk..
        /// </summary>
        public static string LOG_VIEW_UNABLE_READ_FILE {
            get {
                return ResourceManager.GetString("LOG_VIEW_UNABLE_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string LOGGEDIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGGEDIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login. Redirecting to login screen.
        /// </summary>
        public static string LOGIN_FAILED_RELOGIN {
            get {
                return ResourceManager.GetString("LOGIN_FAILED_RELOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_covidien {
            get {
                object obj = ResourceManager.GetObject("logo_covidien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT_BUTTON {
            get {
                return ResourceManager.GetString("LOGOUT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm log out request.
        /// </summary>
        public static string LOGOUT_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("LOGOUT_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        public static string LOGOUT_MSGBOX_TITLE {
            get {
                return ResourceManager.GetString("LOGOUT_MSGBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit the changes?.
        /// </summary>
        public static string MESSAGE_BOX_CONFIRMATION_TEXT_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_CONFIRMATION_TEXT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MESSAGE_BOX_CONFIRMATION_TITLE_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_CONFIRMATION_TITLE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both username and password are required.
        /// </summary>
        public static string MISSING_LOGIN_CREDENTIALS {
            get {
                return ResourceManager.GetString("MISSING_LOGIN_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent service is not detected or unresponsive..
        /// </summary>
        public static string NO_AGENT_APPLICATION_CLOSE_MSG1 {
            get {
                return ResourceManager.GetString("NO_AGENT_APPLICATION_CLOSE_MSG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the internet connection. Application will close..
        /// </summary>
        public static string NO_AGENT_APPLICATION_CLOSE_MSG2 {
            get {
                return ResourceManager.GetString("NO_AGENT_APPLICATION_CLOSE_MSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Viewer.
        /// </summary>
        public static string NOTES_VIEWER_FORM_TITLE {
            get {
                return ResourceManager.GetString("NOTES_VIEWER_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override EST?.
        /// </summary>
        public static string OVERRIDE_EST_QUESTION {
            get {
                return ResourceManager.GetString("OVERRIDE_EST_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string PACKAGE_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("PACKAGE_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages Available.
        /// </summary>
        public static string PACKAGES_AVAILABLE_LABEL {
            get {
                return ResourceManager.GetString("PACKAGES_AVAILABLE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passcode didn&apos;t match.
        /// </summary>
        public static string PASSCODE_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSCODE_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_back_w_arrow {
            get {
                object obj = ResourceManager.GetObject("PB980_back_w_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_back_wo_arrow {
            get {
                object obj = ResourceManager.GetObject("PB980_back_wo_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_connected {
            get {
                object obj = ResourceManager.GetObject("PB980_connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_ESS_splash_screen {
            get {
                object obj = ResourceManager.GetObject("PB980_ESS_splash_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_faded {
            get {
                object obj = ResourceManager.GetObject("PB980_faded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB980_VENTILATOR {
            get {
                object obj = ResourceManager.GetObject("PB980_VENTILATOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PB980ESSicon_text_64 {
            get {
                object obj = ResourceManager.GetObject("PB980ESSicon_text_64", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Logs From The Device.
        /// </summary>
        public static string REQUESTING_DEVICE_LOGS_STATUS_MSG {
            get {
                return ResourceManager.GetString("REQUESTING_DEVICE_LOGS_STATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting ....
        /// </summary>
        public static string REQUESTING_STATUS {
            get {
                return ResourceManager.GetString("REQUESTING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Status.
        /// </summary>
        public static string RSA_AGENT_STATUS {
            get {
                return ResourceManager.GetString("RSA_AGENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All server requests not completed. Close anyway?.
        /// </summary>
        public static string RSA_ALL_REQUESTS_NOT_COMPLETED_WARNING {
            get {
                return ResourceManager.GetString("RSA_ALL_REQUESTS_NOT_COMPLETED_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Session.
        /// </summary>
        public static string RSA_CLOSE_SESSION {
            get {
                return ResourceManager.GetString("RSA_CLOSE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Agent.
        /// </summary>
        public static string RSA_CONNECT {
            get {
                return ResourceManager.GetString("RSA_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection To Agent Failed.
        /// </summary>
        public static string RSA_CONNECT_FAILURE {
            get {
                return ResourceManager.GetString("RSA_CONNECT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected To Agent.
        /// </summary>
        public static string RSA_CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("RSA_CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Session.
        /// </summary>
        public static string RSA_OPEN_SESSION {
            get {
                return ResourceManager.GetString("RSA_OPEN_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Session Not Available.
        /// </summary>
        public static string RSA_SESSION_OPEN_FAILURE {
            get {
                return ResourceManager.GetString("RSA_SESSION_OPEN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected To Server.
        /// </summary>
        public static string RSA_SESSION_OPEN_SUCCESS {
            get {
                return ResourceManager.GetString("RSA_SESSION_OPEN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on Server.
        /// </summary>
        public static string RSA_WAITING_ON_SERVER {
            get {
                return ResourceManager.GetString("RSA_WAITING_ON_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma Separated Value|*.csv|XML|*.xml|All Files|*.*.
        /// </summary>
        public static string SAVE_FILE_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("SAVE_FILE_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log File,.
        /// </summary>
        public static string SAVE_FILE_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("SAVE_FILE_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to File.
        /// </summary>
        public static string SAVE_TO_FILE_BUTTON {
            get {
                return ResourceManager.GetString("SAVE_TO_FILE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second(s) Remaining.
        /// </summary>
        public static string SECONDS_REMAINING {
            get {
                return ResourceManager.GetString("SECONDS_REMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Mode.
        /// </summary>
        public static string SERVICE_MODE {
            get {
                return ResourceManager.GetString("SERVICE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline passcode change is Failed.
        /// </summary>
        public static string SETTINGS_OFFLINE_CHANGE_PASSWORD_FAILURE {
            get {
                return ResourceManager.GetString("SETTINGS_OFFLINE_CHANGE_PASSWORD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline passcode changed successfully.
        /// </summary>
        public static string SETTINGS_OFFLINE_CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("SETTINGS_OFFLINE_CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change offline passcode is allowed only with online login.
        /// </summary>
        public static string SETTINGS_STATUS_ALLOWED_IN_ONLINE {
            get {
                return ResourceManager.GetString("SETTINGS_STATUS_ALLOWED_IN_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Update Package.
        /// </summary>
        public static string SOFTWARE_PACKAGE_INVALID {
            get {
                return ResourceManager.GetString("SOFTWARE_PACKAGE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Package: .
        /// </summary>
        public static string SOFTWARE_UPDATE_TO_STRING {
            get {
                return ResourceManager.GetString("SOFTWARE_UPDATE_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is in progress. Please wait...
        /// </summary>
        public static string SPLASH_SCREEN_AUTHENITICATE_WAIT {
            get {
                return ResourceManager.GetString("SPLASH_SCREEN_AUTHENITICATE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string STATUS_COMPLETE {
            get {
                return ResourceManager.GetString("STATUS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect internet.
        /// </summary>
        public static string STATUS_CONNECT_INTERNET {
            get {
                return ResourceManager.GetString("STATUS_CONNECT_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string STATUS_CONNECTED {
            get {
                return ResourceManager.GetString("STATUS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string STATUS_DISCONNECTED {
            get {
                return ResourceManager.GetString("STATUS_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not disconnect internet.
        /// </summary>
        public static string STATUS_DO_NOT_DISCONNECT {
            get {
                return ResourceManager.GetString("STATUS_DO_NOT_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading..
        /// </summary>
        public static string STATUS_DOWNLOADING {
            get {
                return ResourceManager.GetString("STATUS_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading halted..
        /// </summary>
        public static string STATUS_DOWNLOADING_HALT {
            get {
                return ResourceManager.GetString("STATUS_DOWNLOADING_HALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STATUS_ERROR {
            get {
                return ResourceManager.GetString("STATUS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string STATUS_IDLE {
            get {
                return ResourceManager.GetString("STATUS_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient space on disk.
        /// </summary>
        public static string STATUS_INSUFFICIENTSPACE {
            get {
                return ResourceManager.GetString("STATUS_INSUFFICIENTSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving.
        /// </summary>
        public static string STATUS_RECEIVING {
            get {
                return ResourceManager.GetString("STATUS_RECEIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string STATUS_RUNNING {
            get {
                return ResourceManager.GetString("STATUS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string STATUS_SCHEDULED {
            get {
                return ResourceManager.GetString("STATUS_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitting.
        /// </summary>
        public static string STATUS_TRANSMITTING {
            get {
                return ResourceManager.GetString("STATUS_TRANSMITTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string STATUS_UNAVAILABLE {
            get {
                return ResourceManager.GetString("STATUS_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string STATUS_UNKNOWN {
            get {
                return ResourceManager.GetString("STATUS_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Package Download succeeded. Location is  .
        /// </summary>
        public static string SW_OTHERPACKAGE_DOWNLOAD_DONE_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("SW_OTHERPACKAGE_DOWNLOAD_DONE_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Package Download Failed.
        /// </summary>
        public static string SW_OTHERPACKAGE_DOWNLOAD_FAILED_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("SW_OTHERPACKAGE_DOWNLOAD_FAILED_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Packages Download Completed.
        /// </summary>
        public static string SW_PACKAGE_DOWNLOAD_COMPLETE {
            get {
                return ResourceManager.GetString("SW_PACKAGE_DOWNLOAD_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Packages Download Failed. Restart ESS Application..
        /// </summary>
        public static string SW_PACKAGE_DOWNLOAD_FAILURE {
            get {
                return ResourceManager.GetString("SW_PACKAGE_DOWNLOAD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Packages Download In Progress....
        /// </summary>
        public static string SW_PACKAGE_DOWNLOAD_INPROGRESS {
            get {
                return ResourceManager.GetString("SW_PACKAGE_DOWNLOAD_INPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string SW_UPDATE_CURRENT_VERSION {
            get {
                return ResourceManager.GetString("SW_UPDATE_CURRENT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string SW_UPDATE_FLASH_DEVICE_BUTTON {
            get {
                return ResourceManager.GetString("SW_UPDATE_FLASH_DEVICE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Device.
        /// </summary>
        public static string SW_UPDATE_FLASHING_STATUS_MSG {
            get {
                return ResourceManager.GetString("SW_UPDATE_FLASHING_STATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Device Update Packages....
        /// </summary>
        public static string SW_UPDATE_REQUESTING_PACKAGE_LIST_STATUS_MSG {
            get {
                return ResourceManager.GetString("SW_UPDATE_REQUESTING_PACKAGE_LIST_STATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string SW_UPDATE_SELECT_PACKAGE {
            get {
                return ResourceManager.GetString("SW_UPDATE_SELECT_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Document.
        /// </summary>
        public static string SW_UPDATE_VIEW_DOCUMENT_BUTTON {
            get {
                return ResourceManager.GetString("SW_UPDATE_VIEW_DOCUMENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SW_UPLOAD_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("SW_UPLOAD_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Upload.
        /// </summary>
        public static string SW_UPLOAD_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("SW_UPLOAD_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device update succeeded. To complete device update, please do the following:
        ///a) Power off the ventilator and disconnect AC power
        ///b) Remove and re-install ventilator batteries
        ///c) Reconnect AC power and restart ventilator in Service Mode
        ///d) Reconnect ESS to the ventilator.
        /// </summary>
        public static string SW_UPLOAD_DONE_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("SW_UPLOAD_DONE_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Succeeded.
        /// </summary>
        public static string SW_UPLOAD_DONE_MSGBOX_TITLE {
            get {
                return ResourceManager.GetString("SW_UPLOAD_DONE_MSGBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Failure.
        /// </summary>
        public static string SW_UPLOAD_FAILED_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("SW_UPLOAD_FAILED_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Update Failed.
        /// </summary>
        public static string SW_UPLOAD_FAILED_MSGBOX_TITLE {
            get {
                return ResourceManager.GetString("SW_UPLOAD_FAILED_MSGBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string SW_UPLOAD_SELECT_DOCUMENT_LABEL {
            get {
                return ResourceManager.GetString("SW_UPLOAD_SELECT_DOCUMENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SW_UPLOAD_START_BUTTON {
            get {
                return ResourceManager.GetString("SW_UPLOAD_START_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting translation of log,.
        /// </summary>
        public static string TRANSLATE_LOG_MSG {
            get {
                return ResourceManager.GetString("TRANSLATE_LOG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string UNKNOWN_STATUS {
            get {
                return ResourceManager.GetString("UNKNOWN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complete.
        /// </summary>
        public static string UPDATE_COMPLETE {
            get {
                return ResourceManager.GetString("UPDATE_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string UPDATE_DONE {
            get {
                return ResourceManager.GetString("UPDATE_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Log.
        /// </summary>
        public static string UPLOAD_LOG_BUTTON {
            get {
                return ResourceManager.GetString("UPLOAD_LOG_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload To Server Failure.
        /// </summary>
        public static string UPLOAD_TO_SERVER_FAILURE {
            get {
                return ResourceManager.GetString("UPLOAD_TO_SERVER_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating User.
        /// </summary>
        public static string USER_AUTHENTICATION_REQUEST {
            get {
                return ResourceManager.GetString("USER_AUTHENTICATION_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string USER_LOGIN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("USER_LOGIN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string USER_LOGOUT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("USER_LOGOUT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string USER_NAME_LABEL {
            get {
                return ResourceManager.GetString("USER_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilator Operational Hours.
        /// </summary>
        public static string VENTILATOR_OP_HOURS {
            get {
                return ResourceManager.GetString("VENTILATOR_OP_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilator Preventative Maintenance Hours.
        /// </summary>
        public static string VENTILATOR_PM_HOURS {
            get {
                return ResourceManager.GetString("VENTILATOR_PM_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VERSION_LABEL {
            get {
                return ResourceManager.GetString("VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string VIEW_BUTTON {
            get {
                return ResourceManager.GetString("VIEW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Logs.
        /// </summary>
        public static string VIEW_LOGS_BUTTON {
            get {
                return ResourceManager.GetString("VIEW_LOGS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VTS_Branding {
            get {
                object obj = ResourceManager.GetObject("VTS_Branding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VTS_Splash_Screen {
            get {
                object obj = ResourceManager.GetObject("VTS_Splash_Screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string WORK_LIST_BUTTON {
            get {
                return ResourceManager.GetString("WORK_LIST_BUTTON", resourceCulture);
            }
        }
    }
}
