//*
//*  File:            IpiErrorCodes.cs
//*  Product:         Integrated Patient Intelligence
//*  Module:          InformaticsCore
//*
//*  Description:     Error Codes
//*
//*  $Author: bill.jordan2 $
//*  $Revision: #8 $
//*  $Date: 2012/07/06 $
//*
//*  Copyright:       (c) 2011 - 2012 Nellcor Puritan Bennett LLC.
//*                   This document contains proprietary information to Nellcor Puritan Bennett LLC.
//*                   Transmittal, receipt or possession of this document does not express, license,
//*                   or imply any rights to use, design or manufacture from this information.
//*                   No reproduction, publication, or disclosure of this information, in whole or in part,
//*                   shall be made without prior written authorization from Nellcor Puritan Bennett LLC.


namespace Covidien.Ipi.InformaticsCore
{
    public enum IpiEventCode : int
    {
        TestListenerWrite = 2,
        InvalidDemoCode = 3,
        IpiBaseException,

        BaseErrorCode = 10000,
        ApplicationStartUp,
        ApplicationShutdown,
        AssertNotNullError,
        AssertFailError,
        IntParseError,
        AttemptingToConnectToDatabase,


        InformaticsCore = 20000,
        NoConnectionFoundForId,
        NoConnectionFoundForIdByPortType,
        NoConnectionMissingPortType,
        NoConnectionMissingUid,
        ErrorOpeningTcpListener,
        ConnectionDefinitionUnexpectedContent,
        ErrorCreatingDeviceManagerProcessor,
        StringConverterError,
        ApplicationLogging,
        UnableToLoadReferenceData,
        LoadAssemblyLog,
        LoadAssemblyLogThroughEachType,
        HandleDataReceivedEventLog,
        WaitingForClientConnectionLog,
        IpiThreadLaunchFailure,
        IpiThreadLaunchRunFailure,


        DeviceManagement = 30000,
        ProtocolUidNull,
        PortTypeMissing,
        ProtocolDefinitionUnexpectedContent,
        MissingData,
        ErrorGettingDeviceStatus,
        EmptyDeviceStatusEntity,  
        NoDllFileFound,
        ErrorLoadingProtocolFiles,
        BadProtocolType,
        InvalidProtocolType,
        InvalidProtocolPath,
        CorruptMessageFound,
        NoTypeLoaded,
        FileNotFound,
        DirectoryOrFileNotFound,
        ErrorCreatingTable,
        ErrorConvertingStatusToEntity,
        BadStatusMessage,
        ErrorSettingEntityProcessor,
        ErrorSavingDeviceStatus,
        ErrorLoadingAsseblyTypes,
        ConnectionBroken1,
        ConnectionBroken2,
        ProtocolIOFailure,
        ProtocolTimedOut,
        ProtocolStartupFailure,
        TooManyCorruptMessages,
        AttemptingProtocolDetection,
        ProtocolDetectionSwapSuccessful,
        UnableToDetectNewDifferentProtocol,
        NotAllowedToAttemptProtocolCorrection,
        DeviceHandlerThreadStart,
        AsciiProtocolHandlerProcessDataError,
        NewLineNotDetectedInData,
        BeanBuilderCreatedBeanTypes,
        ConnectionCleanup,
        ProtocolCleanup,
        ConnProtocolPairCleanupUnsupportedConnection,
        ConnProtocolPairCleanupUnsupportedProtocol,
        DeviceCleanupNoSupportedProtocol,
        ResolveEventHandlerStart,
        ResolveEventHandlerAssemblyPath,
        ResolveEventHandlerLoadAssembly,
        ResolveEventHandlerMissingAssembly,
        CreateProtocolHandlerDumpType,
        GetConsistencyDateCheck,
        GetConsistencyDateCheckDirectory,
        ResolveDllEventHandler,
        SqlTransform,
        HbmTransform,
        ClassTransform,
        LoadProtocolFile,
        CreateProtocolHandlerDumpAssembly,
        ResolveEventHandlerAssemblyInfo,
        WorkerThreadTerminating,
        HandleDataReceivedEvent,
        LoadXMLFileProtocols,
        LoadXMLFileDevices,
        LoadXMLStrBeanTypes,
        LoadXMLStrWaveforms,
        LoadXMLFileConfig,
        LoadXMLFileSettings,
        ProcessRequestMessageQueueUnhandledMessage,
        UnProcessedOutgoingMessage,
        UnProcessedMessage,
        DeviceNotStopped,
        DeviceHandlerThreadException,
        DequeueThreadError,
        DequeueThreadProgrammingError,
        DequeueThreadDeviceHandlerMissing,
        CreateTablesLogging,
        LoadConnections,
        LoadProtocols,
        LoadDevices,
        LoadListeners,
        LaunchListenersPortType,
        LaunchListenersCreation,
        StartRawDataSave,
        StopRawDataSave,
        DeviceErrorMessage,
        DeviceUncommonMessage,



        BusinessObjectsCore = 40000,
        InvalidPublisherDefinition,
        InvalidSubscriberDefinition,
        SubscriberExceptionThrown,
        InvalidSectionName,
        InvalidKeyName,
        InvalidAttributeName,
        InvalidValue,
        NoListenerDefinitionFoundForId,
        NoListenerDefinitionFound,
        BadListenerDefinitionFoundForId,
        ListenerDefinitionUnexpectedContent,
        ErrorWhileListening,
        ErrorGettingUnAssociatedDevices,
        ErrorSearchingDeviceBySerialNumber,
        ErrorSearchingDeviceBySessionId,
        ErrorSearchingDeviceByDeviceIds,
        ErrorUpdatingDevicePatientAssociations,
        ErrorUnAssociatingDevices,
        MultipleDevicesFoundForSerialNumber,
        MultipleDevicesFoundForSesionId,
        ErrorFindingPatientByExternalId,
        ErrorFindingPatientByMonitoringSessionId,
        ErrorFindingPatientByPatientId,
        ErrorGettingAllPatients,
        ErrorFindingPatientByPatientSessionId,
        ErrorValidatingPatientDeviceInfo,
        ErrorCreatingNewPatientSession,
        ErrorSavingPatientInfo,
        ErrorGettingAllActivePatientsInfo,
        ErrorGettingActiveAssignments,
        ErrorTerminatingPatientSessionId,
        ErrorGetActivelymonitoredPatients,
        ErrorGetActivelymonitoredPatientsByPatientSessionId,
        MultipleSessionsFoundForPatient,
        ErrorLoadingAllUnAssignedPatients,
        ErrorLoadingAllTherapistsForCurrentUser,
        ErrorGettingAllPatientsForTherapistName,
        ErrorGettingAllPatientsForTherapistId,
        ErrorAssigningPatientsToTherapist,
        ErrorUpdatingPatientTherapistAssignment,
        ErrorGettingAllReports,
        TcpListenerDeviceCreatorListeningThreadStart,
        MultipleTherapistPatientAssignmentsExist,
        GetAllPatientsForTherapists,
        AssignPatientsToTherapistId,
        AssignPatientToTherapist,
        AssignPatientToTherapistError,
        UnAssignPatientFromTherapist,
        UnAssignPatientsFromTherapist,
        UnAssignPatientFromTherapistError,
        RemoveAllAssignments,
        PatientTherapistAssignment,
        RoleSaveError,
        GetFilteredPatientsDeviceStatusError,
        ErrorGettingMonitoredDevicesForPatient,
        FindPatientByExternalIdError,
        UpdateDeviceAssociations,
        UpdateDeviceAssociationsNew,
        TcpListenerDeviceCreatorListen,
        TcpListenerDeviceCreatorClientConnectionReceived,
        TerminatePatientDeviceAssociationError,
        TerminatePatientSessionError, 
        TerminateDeviceSessionByGuidError,
        ParseAlarmsDuplicateAlarms,
        ParseAlarmsBadParse,


        DataAccessLayerErrorCodes = 50000,
        UnableToConnectToDB,
        UnableToOpenAssemblyForDB,
        UnableToExpandDBSession,
        UnableToOpenDBSession,
        UnableToRebuildDBSession,
        SuccessfullyOpenedSessionToDB,
        VentilationQueryIERatioUnexpectedFormat,
        GetAlarmTypeDescriptiveText,


        DeviceSessionManagement = 55000,
        DefaultDeviceSessionFailure,
        InvalidDeviceSession,
        InvalidProtocolUID,
        InvalidProtocolName,
        MultipleProtocolsForUID,
        MultipleProtocolsForName,
        InvalidDeviceTypeName,
        MultipleDeviceTypesForName,
        MultipleDevicesForTypeSerialNumber,
        FailureToProcessEntities,
        FailureToProcessEntitiesSPDP,   // same msg in the Store Publish Device Processor
        UnableToCleanlyCloseDMSDueToSession,
        DeviceSessionManagementAlarmStart = 55013,  // This value is used explicitly in reports
        DeviceSessionManagementAlarmStop = 55014, // This value is used explicitly in reports
        DeviceSessionManagementDeviceSettingsChanged = 55015, // This value is used explicitly in reports
        DeviceInappropreatelyReaped,
        DeviceInappropreatelyDestroyed,
        DeviceInappropreatelyEndded,
        InvalidDeviceMonitoringSessionID,
        SqlExceptionValidatingDeviceMonitoringSession,
        SqlExceptionCreatingDeviceMonitoringSession,
        SqlExceptionSaveRawData,
        SqlExceptionSavingDeviceData,
        DeviceMonitoringSessionUnknownException,
        InvalidDeviceSettingChangeID,
        UnableToSaveDeviceSettingChanges,
        UnableToReconnectDevice,
        UnableToGetAllDeviceCategories,
        UnableToGetAllDeviceTypes,
        UnableToSaveAllDeviceSessions,
        UnableToMakeDevicePrimary,
        UnableToUpdateDeviceRankings,
        UnableToAddNewDeviceToRankings,
        UnableToUpdateAllRankings,
        DeviceSessionReaperReaped,
        UnableToCloseDeviceStatusRecord,
        MultipleDevicesForTypeIPAddressFound,
       

        DeviceProtocols = 60000,
        DualProtocolPattern,
        CorruptMessageReceived, // Note: we will only specify generic error types here for protocols and the associated string will have to further identify origination
        BadRawData,
        ParseBlankableDoubleError,
        ParseBlankableIntError,
        FirstEntitiesReceived,


        IPIUserConfigFileError = 65000,
        IPIUserSaveError,
        IPIUserDeleteError,
        IPIUserValidateError,
        IPIUserGetAllError,
        IPIUserGetUserByEmailError,
        IPIUserGetUserByEmailMultipleUsersError,
        IPIUserGetUserByAccountId,
        IPIUserGetUserByUserNameError,
        IPIUserGetRightsError,
        CheckIfUserCanBeDeletedError,
        IPIRoleGetRoleByRoleGuidError,
        IPIRoleGetRoleByRoleIdError,
        IPIRoleGetRoleByRoleNameError,
        IPIRoleGetRolesForUserError,
        IPIRoleGetAllRolesError,
        IPIRoleGetAllRoleNamesError,
        IPIRoleRemoveUserFromRoleError,
        IPIRoleIsUserInRoleError,
        IPIRoleGetAllRoleNamesByAccountlIdError,
        IPIRoleAddUserToRoleError,

        
        
        ServiceRequestManagerError = 68000,
        MessageExpired,
        ServiceRequestMessageNotHandled,
        ServiceRequestBaseMessageNotHandled,
        DefaultServiceRequrestMessageCreated,




        
        InformaticsWebNoError = 70000,
        InformaticsWebGetEditUserError,
        InformaticsWebSaveEditUserError,
        InformaticsWebSaveCreatedUserError,
        InformaticsWebUnassignRoleError,
        InformaticsWebAssignRoleError,
        InformaticsWebSaveAssignedRolesError,
        InformaticsWebUserCreatedEvent,
        InformaticsWebUserEditedEvent,
        InformaticsWebPasswordChanged,
        InformaticsWebRolesAssignedToUser,
        InformaticsWebCreateRoleError,
        InformaticsWebUnassignUserFromRoleError,
        InformaticsWebAssignUserToRoleError,
        InformaticsWebUsersAssignedToRole,
        InformaticsWebSaveAssignedUsersError,
        InformaticsWebRemoveRoleError,
        InformaticsWebCreatRoleSuccess,
        InformaticsWebServiceRequestLog,
        DeviceAndPatientStatusPageLoad,
        DevicePatientAssociationPageLoad,
        UserAdminListPageLoad,
        UserAdminPageLoad,
        VentSummaryPageLoad,
        MonitoredPatients_TilesPageLoad,
        MonitoredPatients_TablePageLoad,
        AlarmsViewPageLoad,
        InformaticsWebRemoveRoleSuccess, 
        InformaticsWebGetAllUnAssociatedDevicesError,
        InformaticsWebSearchForDeviceByDeviceMonitoringSessionIdError,
        InformaticsWebUpdateDeviceAssociationError,
        InformaticsWebPatientTherapistAssignmentError,
        InformaticsWebFindPatientByExternalIdError,
        InformaticsWebFindPatientByMonitoringSessionIdError,
        InformaticsWebSaveOrUpdatePatientInfoError,
        InformaticsWebPatientAssignmentError,
        InformaticsWebGetAllUnassignedPatientsError,
        InformaticsWebGetAllTherapistsForCurrentUserError,
        InformaticsWebGetAllAssignmentsForUserIdError,
        InformaticsWebGetActiveAssignmentsError,
        InformaticsWebGetAllPatientsAssignedToTherapistError,
        InformaticsWebGetAllMonitoredPatientsError,
        InformaticsWebGetCurrentPatientAlarmsError,
        UnableToGetDeviceList,
        UnableToGetDevicePerformStatistics,
        InformaticsWebUserLoggedIn = 70043, // This value is used explicitly in reports
        InformaticsWebUserLoggedOut = 70044, // This value is used explicitly in reports
        InformaticsWebUserViewingSettingChanges = 70045, // This value is used explicitly in reports
        InformaticsWebUserViewingPatientDetail = 70046,  // This value is used explicitly in reports
        ResetPasswordError,
        ErrorGettingUserInformationByUserName,
        ChangeActivationStatusError,
        ErrorChangingPassword,
        UnlockUserError,
        GetPatientInfoAndSaveEntity,
        EndPatientDeviceAssociation,
        EndPatientMonitoringSession,
        UserAdminUpdateError,
        GetItemByUserIdError,
        UpdateUserError,
        SetOperationalUserLog,
        InformaticsWebErrorGettingDmsIdFromXml,
        InformaticsWebErrorGettingUserNameFromXml,
        PatientTherapistAssignmentPageLoad,
        ReportPageLoad,
        EventsViewPageLoad,
        AdminHomePageLoad,
        AdminReportsPageLoad,
        AdminDevicesPageLoad,
        MonitorAboutPageLoad,
        AdminAboutPageLoad,
        MonitorChangePasswordPageLoad,
        AdminChangePasswordPageLoad,
        InformaticsWebCurrentUserNullError,
        InformaticsWebUserHasNoRightsToDefaultPages,
        InvalidResourceManager,

        DeveloperDemoApp = 75000,
        DeviceDataManagerDemoLoopThreadStart,
        DeviceDataManagerUpdateLoopThreadStart,
        DeviceStatusDialogUpdateLoopThreadStart,

        ExternalSystemsAdapter = 76000,
        ExternalSystemsGateway = 77000,

        MembershipProviders = 80000,
        MembershipProvidersUserValidationFailure,
        MembershipProvidersInitializeFailure,

        IpiCleansingService = 90000,
        IpiCleansingServiceDllLoadFail,
        IpiCleansingServiceDllFolderDoesNotExist,
        IpiCleansingServiceFailedToLoadScheduleFromConfig,
        IpiCleansingServicePluginListAddError,
        IpiCleansingServicePluginExecuteError,
        IpiCleansingServiceError,
        IpiCleansingServiceStrongNameVerificationError,
        IpiCleansingServicePublicKeyTokenError,
        IpiCleansingServicePluginFailedToLoadConfig,
        IpiCleansingServiceUnhandledException,
        IpiCleansingServiceFailedToInstatiateQuery,
        IpiCleansingServiceOpenRawFileFailed,
        IpiCleansingServiceDeleteRawFileFailed,
        IpiCleansingServiceCopyRawFileFailed,
        IpiCleansingSessionsStarted,
        IpiCleansingSessionsDeviceSessionDeletionStarted,
        IpiCleansingSessionsDeviceSessionDeletionEnded,
        IpiCleansingSessionsEnded,


        PluginThreadStart = 100000,
        PluginThreadException,
        PluginThreadTermination,
        PluginDllFolderDoesNotExist,
        PluginDllLoadFail,

        SIRSEarlyIdProtocolHandlerProcessDataError = 100100,


        ParameterManagerStart = 100200,
        BlipWaveThreadException,
        BlipWaveProcessorRunException,
        ExceptionEncoounterInBlipWaveProcessorThread,
        BlipWaveProcessMessageException,
        BlipWaveQueueSizeExceeded,
        SetCommandObjectFailure,
        UnableToPublishShipData,
        ProgramManagerRunAlgorithmError,
        ProgramManagerStopAlgorithmError,
        ProgramManagerSendNullMessageError,
        ProgramManagerReceivedNullMessageError,
        ProgramManagerNoPAMsAssignedInConfig,
        PamSpdErrBadVariable,
        PamSpdErrorBadPointer,
        PamSpdErrorParmeterValue,
        PamSpdErrorUnexpected,
        PamSpdErrorTimeout,
        PamSpdErrorDataOutOfRange,
        PamSpdRecovertFatalDontUseIt,
        PamSpdRecoveryInfoCorrected,
        PamSpdRecoveryNoError,
        PamSpdInitializeFailed,
        PamSpdIndexLowLimitError,
        PamSpdIndexMediumLimitError,
        PamSpdIndexHighLimitError,
        PamSpdIndexGetLowLimitError,
        PamSpdIndexGetMediumLimitError,
        PamSpdIndexGetHighLimitError,
        PamSpdIndexSetLimitError,
        PamSpdIndexGetLimitError,
        PamSpdToleranceError,
        PamSpdGetToleranceError,
        PamSpdAudioEnableError,
        PamSpdGetAudioEnableError,
        PamSpdLoadOxiSmartReportError,
        PamSpdSetResponseModeError,
        PamSpdGetResponseModeError,
        PamSpdResetError,
        PamSpdExecuteError,
        PamSpdSoftwareVersionError,
        PamSatPatternDetectionSetupCallbackError,
        PamSatPatternDetectionSetLowIndexLimitError,
        ParameterManagerUnableToSendMessage,
        PAMRespirationRateWorkerThreadNullIntfc,
        PAMRespirationRateNullOutputHandler,
        PAMRespirationRateWorkerThreadUnresponsive,
        PAMSetHandlersFailure,
        PAMFactoryUnableToCreatePam,
        PAMMessageIOModuleMessageHandlersFailure,
        PAMRespirationRateInvalidAlarmLimits,
        PAMRespirationRateStateChangeError,
        PAMRespirationRateReceivedErrorFromRRInterface,
        PAMRespirationRateDMessageCollectModeComand,
        PAMPulseRateDelayInvalidLimit,
        PAMUnableToTransmitMessage,



        // Any additional "normal" codes go here



        // Debug / Trace message identifiers go here.  These are intended for dynamic filtering (prior to saving to the DB)

        // Might choose to model these after the number sequence of the primaries above... just haven't done so yet.

        IpiTraceGeneralStart = 200000,
        // specific trace elements go here
        IpiTraceGeneralFinal,

        IpiTraceDeviceManagementStart = 210000,
        // specific trace elements go here
        IpiTraceDeviceManagementFinal,

        IpiTraceDeviceProtocolStart = 220000,
        IpiTraceDeviceProtocolMsgCnts,
        IpiTraceDeviceProtocolCorruptMessage,
        // specific trace elements go here
        IpiTraceDeviceProtocolFinal,

        //All debug messages use the same event code.
        IpiDebugMessage = 300000,

    }
}
